version: "3.2"  #versi dari skript docker compose

services:
 #menjelaskan service apa saja yang mau dibuat pada docker
  rabbitmq-sub: #membuat container
    image: rabbitmq:3.8-management-alpine #container dengan image rabbitmq versi 3.8 alpine
    container_name: 'rabbitmq-sub' #set nama container
    ports:
        - 5673:5672 #port pada lokal 5673 dan 5672 pada container (rabbitMQ)
        - 15673:15672 #port pada lokal 15673 dan 15672 pada container (management interface)
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/ #volume untuk data
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq  #volume untuk log
    networks:
        - rabbitmq_network  #set network  

  order-sub: #membuat container
    image: rafiannas/order-service:latest #container dengan image dari hub 
    container_name: 'order-sub' #set nama container
    volumes:
      - .:/src  #menyalin berkas dari current ke folder src
    depends_on:
      - "rabbitmq-sub"  #running setelah container rabbitmq-sub
    networks:
      - rabbitmq_network  #set network  

  shipping-sub: #membuat container
    image: rafiannas/shipping-service:latest #container dengan image dari hub 
    container_name: 'shipping-sub' #set nama container
    volumes:
      - .:/src #menyalin berkas dari current ke folder src
    depends_on:
      - "rabbitmq-sub" #running setelah container rabbitmq-sub
    networks:
      - rabbitmq_network #set network  

networks:
  rabbitmq_network:
    driver: bridge #set network jenis bridge